/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dwfms;

import dwfms.collaboration.ethereum.EthereumCollaborationConnector;
import dwfms.collaboration.simple.SimpleConnector;
import dwfms.framework.*;
import dwfms.framework.collaboration.ICollaboration;
import dwfms.framework.references.InstanceReference;
import dwfms.framework.references.UserReference;
import dwfms.model.bpmn.BPMNModel;
import dwfms.model.BPMNToHybridExecutionMachineTransformer;

import java.io.IOException;
import java.util.concurrent.TimeUnit;

public class App {

    public static void main(String[] args) throws InterruptedException {

        System.out.println("App is running...");

//        ethereum();

        simple();
        System.out.println("App stops...");


    }

    static void ethereum() throws InterruptedException {
        UserReference user = new UserReference("0xE076df4e49182f0AB6f4B98219F721Cccc38f9be");

        IModel model = new BPMNModel();
        ITransformer transformer = new BPMNToHybridExecutionMachineTransformer();
        ICollaboration collaboration = new EthereumCollaborationConnector(user.getUserReference());

        DWFMS dWFMS = DWFMS.builder()
                .model(model)
                .transformer(transformer)
                .collaboration(collaboration)
                .build();

        dWFMS.init();

        InstanceReference reference = dWFMS.deployProcessModel();
        System.out.println("Contract Address: " + reference.getInstanceRef());
        // InstanceReference reference = new InstanceReference("0xb709b82a554f07c7916109a0f55D0D6c995DBcc9");

        //dWFMS.getMyWorklist(instance);
        dWFMS.executeTask(new TaskExecution(reference, "A"));
        TimeUnit.SECONDS.sleep(2);
        dWFMS.executeTask(new TaskExecution(reference, "C"));

    }

    static void simple() throws InterruptedException {

        UserReference user = new UserReference("hans");

        IModel model = new BPMNModel();
        ITransformer transformer = new BPMNToHybridExecutionMachineTransformer();
        ICollaboration collaboration = null;
        try {
            collaboration = new SimpleConnector();
        } catch (IOException e) {
            e.printStackTrace();
        }

        DWFMS dWFMS = DWFMS.builder()
                .model(model)
                .transformer(transformer)
                .collaboration(collaboration)
                .build();

        dWFMS.init();

        // model hash fc2d41015d1e84374e0e6ec5dc491c10556c2aa7133e7cdcc3dcd708569587b6
        InstanceReference reference = dWFMS.deployProcessModel();

        //dWFMS.getMyWorklist(instance);
        dWFMS.executeTask(new TaskExecution(reference, "Start"));
        TimeUnit.SECONDS.sleep(2);
        dWFMS.executeTask(new TaskExecution(reference, "A"));
        TimeUnit.SECONDS.sleep(2);
        dWFMS.executeTask(new TaskExecution(reference, "C"));

        System.out.println("App stops...");

    }



}
