/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dwfms;

import dwfms.collaboration.ethereum.EthereumCollaborationConnector;
import dwfms.collaboration.example.SimpleCollaboration;
import dwfms.framework.collaboration.BaseCollaboration;
import dwfms.framework.bpm.model.BaseModel;
import dwfms.framework.core.DWFMS;
import dwfms.framework.bpm.ITransformer;
import dwfms.bpm.BPMNToHybridExecutionMachineTransformer;
import dwfms.ui.HttpInterface;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import java.io.IOException;
import java.net.URL;
import java.security.NoSuchAlgorithmException;

public class App {

    private static final Logger logger = LogManager.getLogger(App.class);

    public static void main(String[] args) throws InterruptedException, NoSuchAlgorithmException, IOException {

        String mode = args[0];
        String user = args[1];
        int port = Integer.parseInt(args[2])+1;

        logger.trace("Mode: " + args[0]);
        logger.trace("User: " + args[1]);
        logger.trace("Port: " + args[2]);

        DWFMS dWFMS = null;
        HttpInterface httpInterface;

        BaseModel model = ExampleDataFactory.exampleBPMNModel();
        ITransformer transformer = new BPMNToHybridExecutionMachineTransformer();
        BaseCollaboration collaboration = null;

        if(mode.equals("simple")) {
            collaboration = new SimpleCollaboration(new URL("http://localhost:" + port));
        }
        else if(mode.equals("eth")) {
             collaboration =new EthereumCollaborationConnector(new URL("http://localhost:8545"), port);
        }

        dWFMS = DWFMS.builder()
                .model(model)
                .transformer(transformer)
                .collaboration(collaboration)
                .build();

        dWFMS.init(ExampleDataFactory.getUserByNameAndMode(user, mode));

        httpInterface = new HttpInterface(dWFMS, Integer.parseInt(args[2]));

    }

}
